# Generated by Django 4.1.1 on 2022-09-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('stock', models.IntegerField()),
                ('validity', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vegetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('stock', models.IntegerField()),
                ('validity', models.DateField()),
            ],
        ),
    ]
